import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/gen.module.css'
import { MetaMaskConnector } from "wagmi/connectors/metaMask";
import { signIn } from "next-auth/react";
import { useAccount, useConnect, useSignMessage, useBalance, useDisconnect } from "wagmi";
import { useRouter } from "next/router";
import { useAuthRequestChallengeEvm } from "@moralisweb3/next"
import { fetchBalance } from '@wagmi/core'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { connectAsync } = useConnect();
    const { disconnectAsync } = useDisconnect();
    const { isConnected } = useAccount();
    const { signMessageAsync } = useSignMessage();
    const { requestChallengeAsync } = useAuthRequestChallengeEvm();
    const { push } = useRouter();

    const handleAuth = async () => {
      if (isConnected) {
        await disconnectAsync();
      }

      const { account, chain } = await connectAsync({
        connector: new MetaMaskConnector(),
      });

      const { message } = await requestChallengeAsync({
        address: account,
        chainId: chain.id,
      });

      const signature = await signMessageAsync({ message });

      const balance = await fetchBalance({
        address: account,
      })

      const { url } = await signIn("moralis-auth", {
        message,
        signature,
        redirect: false,
        callbackUrl: "/user",
      });

      push(url);
      //redirection by push to avoid refreshing
    };

    return (
      <>
        <Head>
          <title>Connect to MetaMask</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
          <h1>NextJS and MetaMask</h1>
          <div className={styles.dispButton}>
            <button onClick={handleAuth}>Connect to Metamask</button>
          </div>
        </main>
      </>
    )
}
